(() => {
  function servicesForKeyword(label) {
    const text = String(label || "").toLowerCase();
    const services = ["FW"];
    if (text.includes("polizei") || text.includes("geiselnahme") || text.includes("amok") || text.includes("schuss") || text.includes("hieb") || text.includes("stich")) services.push("POL");
    return [...new Set(services)];
  }

  function dispositionFor(required, services = []) {
    const counts = new Map();
    (required || []).forEach((type) => counts.set(type, (counts.get(type) || 0) + 1));
    const vehicles = [...counts.entries()].map(([type, count]) => count > 1 ? `${count} ${type}` : `1 ${type}`);
    return [...vehicles, ...(services || [])].join(", ") || "Lage erkunden";
  }

  function linked(label, required, signal = true) {
    const requiredServices = servicesForKeyword(label);
    return {
      label,
      type: "emergency",
      required,
      signal,
      requiredServices,
      disposition: dispositionFor(required, requiredServices)
    };
  }

  const linkedFwRdKeywords = [
    linked("RD 2 / B 2 PERSON - Bau-, Wohncontainer / Person in Gefahr", ["RTW", "NEF"], true),
    linked("RD 2 / B 2 PERSON - Gartenhütte, Schuppen / Person in Gefahr", ["RTW", "NEF"], true),
    linked("RD 2 / B 2 PERSON - Person", ["RTW", "NEF"], true),
    linked("RD 2 / B 2 PERSON - PKW / Person in Gefahr", ["RTW", "NEF"], true),
    linked("RD 2 / B 2 PERSON - PKW / Person in Gefahr auf BAB", ["RTW", "NEF"], true),
    linked("RD 0 / B 3 - Am Gebäude", ["REF"], true),
    linked("RD 0 / B 3 - Brandgeruch (im Gebäude)", ["REF"], true),
    linked("RD 1 / B 3 - Dachstuhl", ["RTW", "RTW"], true),
    linked("RD 0 / B 3 - Dehnfuge", ["REF"], true),
    linked("RD 1 / B 3 - Garage", ["RTW"], true),
    linked("RD 1 / B 3 - Keller", ["RTW", "RTW"], true),
    linked("RD 0 / B 3 - Rauchentwicklung (im Gebäude)", ["REF"], true),
    linked("RD 1 / B 3 - Zimmer", ["RTW"], true),
    linked("RD 0 / B 3 - Berghütte", ["REF"], true),
    linked("RD 0 / B 3 - Fahrzeug / Maschine", ["REF"], true),
    linked("RD 0 / B 3 - LKW/Bus außerorts", ["REF"], true),
    linked("RD 0 / B 3 - LKW/Bus auf BAB", ["REF"], true),
    linked("RD 1 / B 3 - auf B3", ["RTW"], true),
    linked("RD 0 / B 3 - überhitzter Heustock", ["REF"], true),
    linked("RD 3 / B 3 PERSON - Dachstuhl / Person in Gefahr", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / B 3 PERSON - Garage / Person in Gefahr", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / B 3 PERSON - Keller / Person in Gefahr", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / B 3 PERSON - Rauchentwicklung / Person in Gefahr", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / B 3 PERSON - Zimmer / Person in Gefahr", ["RTW", "RTW", "NEF"], true),
    linked("RD 2 / B 3 PERSON - LKW / Person in Gefahr", ["RTW", "NEF"], true),
    linked("RD 2 / B 3 PERSON - LKW / Person in Gefahr auf BAB", ["RTW", "NEF"], true),
    linked("RD 3 / B 3 PERSON - auf B 3 Person", ["RTW", "RTW", "NEF"], true),
    linked("RD 4 / B 4 - ausgedehnt / hoch bis 6.OG", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B 4 - Tiefgarage", ["RTW", "RTW"], true),
    linked("RD 4 / B 4 - Wohnheim", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B 4 - Behinderteneinrichtung", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B 4 - Hochhaus ab 7. OG", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B 4 - Supermarkt", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Kindergarten", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Kino", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Kirche", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Schule", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Theater", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Zirkus", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Sägewerk / Schreinerei", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Lagerhalle", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Silo (kein Gefahrstoff)", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - große Höhe -Turm", ["RTW", "RTW"], true),
    linked("RD 0 / B 4 - große Höhe -Windrad", ["REF"], true),
    linked("RD 1 / B 4 - Bauernhof", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Stall / Scheune", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - Aussiedlerhof", ["RTW", "RTW"], true),
    linked("RD 1 / B 4 - auf B4", ["RTW", "RTW"], true),
    linked("RD 4 / B 4 - Hotel", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B 4 - Industriegebäude", ["RTW", "RTW"], true),
    linked("RD 4 / B 5 - Pflege-/Altenheim", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B 5 - Kaufhaus", ["RTW", "RTW"], true),
    linked("RD 4 / B 5 - Krankenhaus", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B 5 - auf B5", ["RTW", "RTW"], true),
    linked("RD 1 / B 6 - auf B6", ["RTW", "RTW"], true),
    linked("RD 1 / B 7 - auf B7", ["RTW", "RTW"], true),
    linked("RD 1 / B 8 - auf B8", ["RTW", "RTW"], true),
    linked("RD 0 / B BMA - Rauchwarnmelder Hausnotruf", ["REF"], true),
    linked("RD 0 / B BMA - Rauchwarnmelder", ["REF"], true),
    linked("RD 0 / B BOOT - Boot / Yacht / Floß", ["REF"], true),
    linked("RD 4 / B SCHIENENTUNNEL - Zug im Tunnel", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B SCHIENENTUNNEL - S-Bahn im Tunnel", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B SCHIENENTUNNEL - U-Bahn im Tunnel", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B SCHIFF - Passagierschiff", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B SCHIFF - Frachtschiff", ["RTW", "RTW"], true),
    linked("RD 1 / B STRAßENTUNNEL - Tunnel", ["RTW", "RTW"], true),
    linked("RD 1 / B WALD - Wald groß (>1,000m²)", ["RTW"], true),
    linked("RD 1 / B WALD - Bergwald", ["RTW"], true),
    linked("RD 4 / B ZUG - Personenzug", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 1 / B ZUG - Güterzug", ["RTW"], true),
    linked("RD 1 / B ZUG - Zug nur Lokomotive", ["RTW"], true),
    linked("RD 4 / B ZUG - Straßenbahn", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B ZUG - U-Bahn im Freien", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / B ZUG - S-Bahn im Freien", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD AMOK / THL AMOK FW - Amoklage", ["RTW"], true),
    linked("RD 4 / THL GEBÄUDEEINSTURZ - Gebäude eingestürzt", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Person droht zu springen", ["RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Person absturzgefährdet", ["RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Person in Höhe", ["RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Person aus Tiefe / Schacht", ["RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Person auf Windrad / Kran", ["RTW", "NEF"], true),
    linked("RD 2 / THL P RETTUNG H/T - Paraglider / Fallschirmspringer / Drachenflieger abgestürzt", ["RTW", "NEF"], true),
    linked("RD 3 / THL P STRAßENBAHN - Person unter Straßenbahn", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL P STRAßENBAHN - Straßenbahn", ["RTW", "RTW", "NEF"], true),
    linked("RD 2 / THL P STROM - Person Stromunfall", ["RTW", "NEF"], true),
    linked("RD 2 / THL P VERSCHÜTTET - Person verschüttet / Tiefbauunfall", ["RTW", "NEF"], true),
    linked("RD 2 / THL P VERSCHÜTTET - Person in Silo", ["RTW", "NEF"], true),
    linked("RD 0 / THL P EINGESCHLOSSEN - Wohnung öffnen akut", ["REF"], true),
    linked("RD 0 / THL P EINGESCHLOSSEN - Fahrzeug öffnen akut", ["REF"], true),
    linked("RD 3 / THL P ZUG - Person unter Zug", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL P ZUG - Person unter S-Bahn", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL P ZUG - Person vom Zug erfasst", ["RTW", "RTW", "NEF"], true),
    linked("RD 1 / THL 1 - Waldunfall ohne eingeklemmte Person", ["RTW"], true),
    linked("RD 1 / THL 2 - mehrere PKW", ["RTW", "RTW"], true),
    linked("RD 1 / THL 2 - LKW / Bus (leer), ohne eingeklemmte Personen", ["RTW"], true),
    linked("RD 2 / THL 3 - Person eingeklemmt (nicht VU)", ["RTW", "NEF"], true),
    linked("RD 3 / THL 3 - 1 oder 2 PKW, Person eingeklemmt", ["RTW", "RTW", "NEF"], true),
    linked("RD 5 / THL 3 - Bus (besetzt)", ["RTW", "RTW", "RTW", "RTW", "RTW", "RTW", "NEF", "NEF"], true),
    linked("RD 1 / THL 3 - Kran umgestürzt", ["RTW"], true),
    linked("RD 2 / THL 3 - Waldunfall mit eingeklemmter Person", ["RTW", "NEF"], true),
    linked("RD 4 / THL 4 - mehrere PKW, Personen eingeklemmt", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL 4 - LKW / Bus (leer), Person eingeklemmt", ["RTW", "RTW", "NEF"], true),
    linked("RD 5 / THL 5 - Massenkarambolage, Personen einge-klemmt", ["RTW", "RTW", "RTW", "RTW", "RTW", "RTW", "NEF", "NEF"], true),
    linked("RD MANV 10-15 / THL 5 - Bus besetzt mit eingeklemmten Personen", [], true),
    linked("RD 4 / THL 5 - mehrere LKW mit eingeklemmten Personen", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD WASSERNOT 3 / THL WASSER - Rettung Person", ["RTW", "NEF", "RTH"], true),
    linked("RD 4 / THL VU FLUGZEUG 1 - Notlandung", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / THL VU FLUGZEUG 1 - Ballon", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / THL VU FLUGZEUG 1 - Hubschrauber", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 4 / THL VU FLUGZEUG 1 - Kleinflugzeug", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD MANV 10-15 / THL VU FLUGZEUG 2 - Frachtflugzeug", [], true),
    linked("RD MANV 10-15 / THL VU FLUGZEUG 2 - Passagierflugzeug", [], true),
    linked("RD MANV 10-15 / THL VU FLUGZEUG 2 - Militärflugzeug", [], true),
    linked("RD 4 / THL VU SCHIFF KOLLISION - Kollision Passagierschiff", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL VU SCHIFF KOLLISION - Kollision Frachtschiff", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL VU SCHIFF KOLLISION - Kollision Boot / Yacht / Floß", ["RTW", "RTW", "NEF"], true),
    linked("RD 4 / THL VU SCHIFF LECK - Schiff leck Passagierschiff", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 3 / THL VU SCHIFF LECK - Schiff leck Frachtschiff", ["RTW", "RTW", "NEF"], true),
    linked("RD MANV 16-25 / THL VU ZUG - Zug", [], true),
    linked("RD 1 / ABC 3 - große Menge", ["RTW"], true),
    linked("RD 1 / ABC 3 - Gasaustritt brennbar", ["RTW"], true),
    linked("RD 1 / ABC 3 - Gasaustritt im Gebäude", ["RTW"], true),
    linked("RD 3 / ABC B ATOM - Brand Atom im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B ATOM - Brand Atom im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B ATOM - Brand Atom PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 1 / ABC B - Brand Tankstelle", ["RTW", "RTW"], true),
    linked("RD 1 / ABC B - Brand Biogasanlage", ["RTW", "RTW"], true),
    linked("RD 3 / ABC B - Brand Raffinerie", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B - Brand Tanklager", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B - Brand Tankwagen", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Bio im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Bio im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Bio PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Chemie im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Chemie im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Chemie Zug", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC B BIO / CHEMIE - Brand Chemie LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL ATOM - THL Atom Austritt im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL ATOM - THL Atom Austritt im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL ATOM - THL Atom PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL ATOM - THL VU Atom PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Bio Austritt im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Bio Austritt im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Bio PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Chemie Austritt im Gebäude", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Chemie Austritt im Freien", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL Chemie PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL VU Bio PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL VU Chemie PKW / LKW", ["RTW", "RTW", "NEF"], true),
    linked("RD 3 / ABC THL BIO / CHEMIE - THL VU Chemie Zug", ["RTW", "RTW", "NEF"], true),
    linked("RD 4 / ABC EXPLOSION - Explosion / Verpuffung", ["RTW", "RTW", "RTW", "RTW", "NEF"], true),
    linked("RD 0 / B BMA 2 - BMA Krankenhäuser und Altenheime", ["REF"], true),
    linked("RD 1 / THL 3 - e-call ohne Spracherwiederung", ["RTW"], true),
  ];

  window.rdKeywords = [...(window.rdKeywords || []), ...linkedFwRdKeywords];
})();
