window.poiCategoryCatalog = [
  { key: "hospital", label: "Krankenhaus", importable: false },
  { key: "station", label: "Rettungswache", importable: false },
  { key: "practice", label: "Arztpraxis", importable: true },
  { key: "dentist", label: "Zahnarztpraxis", importable: true },
  { key: "dialysis", label: "Dialyse", importable: true },
  { key: "nursing-home", label: "Alten-/Pflegeheim", importable: true },
  { key: "school", label: "Schule", importable: true },
  { key: "kindergarten", label: "Kindergarten", importable: true },
  { key: "university", label: "Universität", importable: true },
  { key: "railway-station", label: "Bahnhöfe", importable: true },
  { key: "fire-station", label: "Feuerwehr", importable: true },
  { key: "police", label: "Polizei", importable: true },
  { key: "townhall", label: "Rathaus", importable: true },
  { key: "church", label: "Kirche", importable: true },
  { key: "cinema", label: "Kino", importable: true },
  { key: "sports-centre", label: "Sportzentrum", importable: true },
  { key: "mall", label: "Einkaufszentrum", importable: true },
  { key: "hotel", label: "Hotel", importable: true },
  { key: "public", label: "Öffentlicher Ort", importable: false },
  { key: "home", label: "Wohnadresse", importable: false }
];
